using System.Text.Json;
using System.Windows.Forms;
using CaYaTrace.Core.Correlation;
using CaYaTrace.Core.Graph;
using CaYaTrace.Core.Model;
using CaYaTrace.Storage;
using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.WinForms;

namespace CaYaTrace.App.Modes;

/// <summary>
/// The workbench window: a WebView2 surface over the same engine the CLI drives.
/// </summary>
/// <remarks>
/// The web layer is a <em>view</em>. It receives already-projected tree nodes and sends
/// back intents; it never touches a session database and never issues a query of its
/// own. Keeping that boundary sharp is what makes the exported HTML report possible —
/// the same markup renders from inlined data with no engine behind it at all.
/// </remarks>
public sealed class WorkbenchWindow : Form
{
    private readonly WebView2 _view;
    private readonly string? _initialSession;
    private SessionStore? _store;

    private static readonly JsonSerializerOptions Json = new()
    {
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
    };

    public WorkbenchWindow(string? sessionPath)
    {
        _initialSession = sessionPath;

        Text = "CaYaTrace";
        Width = 1400;
        Height = 900;
        MinimumSize = new System.Drawing.Size(900, 600);
        StartPosition = FormStartPosition.CenterScreen;

        // Matches the page background so the window does not flash white before the
        // WebView paints — jarring on a dark theme.
        BackColor = System.Drawing.Color.FromArgb(0x11, 0x18, 0x26);

        _view = new WebView2 { Dock = DockStyle.Fill, DefaultBackgroundColor = BackColor };
        Controls.Add(_view);

        Load += async (_, _) => await InitializeAsync();
        FormClosed += (_, _) => _store?.Dispose();
    }

    private async Task InitializeAsync()
    {
        // The user-data folder is set explicitly. WebView2 otherwise creates it beside
        // the executable, which fails the moment CaYaTrace is run the way it is meant
        // to be — from a read-only share, a write-protected stick, or an evidence drive.
        CoreWebView2Environment environment;
        try
        {
            environment = await CoreWebView2Environment.CreateAsync(
                browserExecutableFolder: null,
                userDataFolder: WebViewPaths.UserDataFolder);
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                $"The WebView2 runtime could not be started.\n\n{ex.Message}\n\n" +
                "Install it from https://developer.microsoft.com/microsoft-edge/webview2/ " +
                "or use the command line instead.",
                "CaYaTrace", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            Close();
            return;
        }

        await _view.EnsureCoreWebView2Async(environment);
        CoreWebView2 core = _view.CoreWebView2;

        // The page is local, generated by us, and handles forensic data. It has no
        // reason to reach the network or open developer surfaces in a shipped build.
        core.Settings.AreDevToolsEnabled = false;
        core.Settings.AreDefaultContextMenusEnabled = false;
        core.Settings.IsStatusBarEnabled = false;
        core.Settings.AreBrowserAcceleratorKeysEnabled = false;
        core.Settings.IsPasswordAutosaveEnabled = false;
        core.Settings.IsGeneralAutofillEnabled = false;

        // A session can contain attacker-controlled strings — file paths, URLs, registry
        // data. Navigating away from the local document on the strength of one would be
        // a way for observed content to reach the network.
        core.NavigationStarting += (_, e) =>
        {
            if (!e.Uri.StartsWith("data:", StringComparison.OrdinalIgnoreCase)
                && !e.Uri.StartsWith("about:", StringComparison.OrdinalIgnoreCase))
            {
                e.Cancel = true;
            }
        };
        core.NewWindowRequested += (_, e) => e.Handled = true;

        core.WebMessageReceived += OnWebMessage;

        core.NavigateToString(Assets.Workbench);
    }

    private void OnWebMessage(object? sender, CoreWebView2WebMessageReceivedEventArgs e)
    {
        string raw;
        try { raw = e.TryGetWebMessageAsString(); }
        catch (ArgumentException) { return; }

        string type;
        try
        {
            using JsonDocument doc = JsonDocument.Parse(raw);
            type = doc.RootElement.TryGetProperty("type", out JsonElement t) ? t.GetString() ?? string.Empty : string.Empty;
        }
        catch (JsonException)
        {
            return;
        }

        switch (type)
        {
            case "ready":
                if (_initialSession is not null) LoadSession(_initialSession);
                break;

            case "buildRemovalPlan":
                // Deliberately not wired to anything destructive from the view. The
                // plan is written to disk for review; applying it is a separate,
                // explicit action.
                MessageBox.Show(
                    "Removal-plan export from the workbench lands in 0.2.\n\n" +
                    "For now:\n" +
                    "  CaYaTrace report --session <dir> --export-package plan.ctpkg\n" +
                    "  CaYaTrace remediate --package plan.ctpkg",
                    "CaYaTrace", MessageBoxButtons.OK, MessageBoxIcon.Information);
                break;
        }
    }

    /// <summary>Loads a session and pushes its projected tree to the view.</summary>
    public void LoadSession(string path)
    {
        try
        {
            _store?.Dispose();
            _store = SessionStore.Open(path);

            SessionInfo? session = _store.LoadSessionInfo();
            if (session is null)
            {
                MessageBox.Show($"{path} does not contain a CaYaTrace session.",
                    "CaYaTrace", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            string payload = BuildPayload(_store, session);
            _view.CoreWebView2.PostWebMessageAsString(
                JsonSerializer.Serialize(new { type = "session", payload = JsonDocument.Parse(payload).RootElement }, Json));
        }
        catch (Exception ex) when (ex is IOException or Microsoft.Data.Sqlite.SqliteException)
        {
            MessageBox.Show($"Could not open the session.\n\n{ex.Message}",
                "CaYaTrace", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    /// <summary>
    /// Projects a stored session into the shape the view renders. Shared with the HTML
    /// exporter so the workbench and the report can never disagree.
    /// </summary>
    public static string BuildPayload(SessionStore store, SessionInfo session, CausalGraphOptions? options = null)
    {
        var processes = new ProcessTable();
        foreach (ProcessNode node in store.LoadProcesses()) processes.AddOrUpdate(node);

        var flows = new FlowTable();
        foreach (NetworkFlow flow in store.LoadFlows())
            flows.NoteConnect(flow.Key, flow.Owner, flow.FirstSeen, flow.OwnerEvidence ?? "stored");

        var builder = new CausalGraphBuilder(processes, flows);
        options ??= new CausalGraphOptions
        {
            RootProcess = session.RootProcess == ProcessKey.None ? null : session.RootProcess,
        };
        IReadOnlyList<CausalNode> roots = builder.Build(store.Query(), options);

        return JsonSerializer.Serialize(new { session, tree = roots }, Json);
    }
}
