using System.Text.Json;
using System.Windows.Forms;
using CaYaTrace.Core.Model;
using CaYaTrace.Export;
using CaYaTrace.Storage;
using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.WinForms;

namespace CaYaTrace.App.Modes;

/// <summary>
/// The workbench window: a WebView2 surface over the same engine the CLI drives.
/// </summary>
/// <remarks>
/// <para>
/// The web layer is a <em>view</em>. It receives already-projected data and sends back
/// intents; it never touches a session database and never issues a query of its own.
/// Keeping that boundary sharp is what makes the exported HTML report possible — the
/// same markup renders from inlined data with no engine behind it at all.
/// </para>
/// <para>
/// It also draws the security line in the right place. Everything the page can ask for
/// is an enumerated intent handled here, so a string that arrived from a recorded
/// program cannot become a file path, a command line, or a navigation. The page can ask
/// to remove items from a plan; it cannot name a file to delete.
/// </para>
/// </remarks>
public sealed partial class WorkbenchWindow : Form
{
    private readonly WebView2 _view;
    private readonly UserSettings _settings;
    private readonly string? _initialSession;

    private SessionStore? _store;
    private SessionInfo? _session;
    private string? _sessionPath;

    /// <summary>Section to open on, from <c>--view</c>. Null lets the page decide.</summary>
    public string? InitialView { get; init; }

    /// <summary>
    /// When set, the workbench renders the requested view to a PNG and exits.
    /// </summary>
    /// <remarks>
    /// Captured through WebView2's own preview API rather than off the screen. Copying
    /// from the screen device context requires the window to be visible and in front,
    /// which on a machine somebody is using means the image is whatever they happened
    /// to have open — measured, and it captured a browser session. This path never
    /// reads the screen, so it cannot photograph anything but this page.
    /// </remarks>
    public string? ScreenshotPath { get; init; }

    public WorkbenchWindow(string? sessionPath, UserSettings settings)
    {
        _initialSession = sessionPath;
        _settings = settings;

        Text = "CaYaTrace";
        Width = 1440;
        Height = 940;
        MinimumSize = new System.Drawing.Size(940, 620);
        StartPosition = FormStartPosition.CenterScreen;
        Icon = AppIcon.Load();

        // Matches the page background so the window does not flash white before the
        // WebView paints — jarring on a dark theme.
        BackColor = System.Drawing.Color.FromArgb(0x11, 0x18, 0x26);

        _view = new WebView2 { Dock = DockStyle.Fill, DefaultBackgroundColor = BackColor };
        Controls.Add(_view);

        Load += async (_, _) => await InitializeAsync();
        FormClosing += (_, e) => OnClosingWindow(e);
        FormClosed += (_, _) => Cleanup();
    }

    private async Task InitializeAsync()
    {
        // The user-data folder is set explicitly. WebView2 otherwise creates it beside
        // the executable, which fails the moment CaYaTrace is run the way it is meant
        // to be — from a read-only share, a write-protected stick, or an evidence drive.
        CoreWebView2Environment environment;
        try
        {
            environment = await CoreWebView2Environment.CreateAsync(
                browserExecutableFolder: null,
                userDataFolder: WebViewPaths.UserDataFolder);
        }
        catch (Exception ex)
        {
            MessageBox.Show($"{Strings.T("error.webview_missing")}\n\n{ex.Message}",
                "CaYaTrace", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            Close();
            return;
        }

        await _view.EnsureCoreWebView2Async(environment);
        CoreWebView2 core = _view.CoreWebView2;

        // The page is local, generated by us, and handles forensic data. It has no
        // reason to reach the network or open developer surfaces in a shipped build.
        core.Settings.AreDevToolsEnabled = false;
        core.Settings.AreDefaultContextMenusEnabled = false;
        core.Settings.IsStatusBarEnabled = false;
        core.Settings.AreBrowserAcceleratorKeysEnabled = false;
        core.Settings.IsPasswordAutosaveEnabled = false;
        core.Settings.IsGeneralAutofillEnabled = false;

        // A session can contain attacker-controlled strings — file paths, URLs, registry
        // data. Navigating away from the local document on the strength of one would be
        // a way for observed content to reach the network.
        core.NavigationStarting += (_, e) =>
        {
            if (!e.Uri.StartsWith("data:", StringComparison.OrdinalIgnoreCase)
                && !e.Uri.StartsWith("about:", StringComparison.OrdinalIgnoreCase))
            {
                e.Cancel = true;
            }
        };
        core.NewWindowRequested += (_, e) => e.Handled = true;
        core.DownloadStarting += (_, e) => e.Cancel = true;

        core.WebMessageReceived += OnWebMessage;
        core.NavigateToString(Assets.Workbench);
    }

    /// <summary>Posts a message to the page, marshalling to the UI thread if needed.</summary>
    private void Post(string type, object payload)
    {
        if (IsDisposed || _view.IsDisposed) return;

        if (InvokeRequired)
        {
            try { BeginInvoke(() => Post(type, payload)); }
            catch (ObjectDisposedException) { }
            catch (InvalidOperationException) { }
            return;
        }

        if (_view.CoreWebView2 is null) return;

        try
        {
            _view.CoreWebView2.PostWebMessageAsString(
                JsonSerializer.Serialize(new { type, payload }, SessionProjection.Json));
        }
        catch (ObjectDisposedException) { }
        catch (InvalidOperationException) { }
    }

    private void Toast(string text, string? kind = null) => Post("toast", new { text, kind });

    /// <summary>Renders the current view to a PNG and closes the window.</summary>
    private async Task CaptureAndExitAsync(string path)
    {
        // The session projection and the first paint both land after "ready". Capturing
        // immediately produces a picture of an empty shell.
        await Task.Delay(TimeSpan.FromSeconds(3)).ConfigureAwait(true);

        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);

            using var stream = new MemoryStream();
            await _view.CoreWebView2
                .CapturePreviewAsync(CoreWebView2CapturePreviewImageFormat.Png, stream)
                .ConfigureAwait(true);

            await File.WriteAllBytesAsync(path, stream.ToArray()).ConfigureAwait(true);
            Console.WriteLine(Path.GetFullPath(path));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or InvalidOperationException)
        {
            Console.Error.WriteLine($"cayatrace: could not write {path}: {ex.Message}");
        }
        finally
        {
            Close();
        }
    }

    private void OnWebMessage(object? sender, CoreWebView2WebMessageReceivedEventArgs e)
    {
        string raw;
        try { raw = e.TryGetWebMessageAsString(); }
        catch (ArgumentException) { return; }

        JsonElement payload;
        string type;
        try
        {
            using JsonDocument doc = JsonDocument.Parse(raw);
            type = doc.RootElement.TryGetProperty("type", out JsonElement t) ? t.GetString() ?? string.Empty : string.Empty;
            payload = doc.RootElement.TryGetProperty("payload", out JsonElement pl)
                ? pl.Clone()
                : default;
        }
        catch (JsonException)
        {
            return;
        }

        try
        {
            Dispatch(type, payload);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException
                                      or Microsoft.Data.Sqlite.SqliteException or InvalidOperationException)
        {
            // A handler failing is a bad session, a locked file, or a missing tool — all
            // things the operator can act on. Crashing the workbench over one is not.
            Toast($"{ex.Message}", "error");
        }
    }

    private void Dispatch(string type, JsonElement payload)
    {
        switch (type)
        {
            case "ready":
                SendBoot();
                if (_initialSession is not null) LoadSession(_initialSession);
                if (ScreenshotPath is not null) _ = CaptureAndExitAsync(ScreenshotPath);
                break;

            case "setLanguage":
                string? lang = Str(payload, "language");
                if (Strings.Supports(lang))
                {
                    Strings.Language = lang!;
                    _settings.Language = Strings.Language;
                    _settings.Save();
                }
                break;

            case "relaunchElevated":
                RelaunchElevated();
                break;

            case "pickFile": PickFile(Str(payload, "purpose")); break;
            case "pickFolder": PickFolder(Str(payload, "purpose")); break;

            case "startCapture": StartCapture(payload); break;
            case "stopCapture": StopCapture(); break;

            case "listSessions": ListSessions(Str(payload, "root")); break;
            case "loadSession": LoadSession(Str(payload, "path") ?? string.Empty); break;
            case "deleteSession": DeleteSession(Str(payload, "path")); break;
            case "revealPath": Reveal(Str(payload, "path")); break;

            case "export": ExportSession(payload); break;

            case "buildPlan": BuildPlan(payload); break;
            case "exportPackage": ExportPackage(payload); break;
            case "applyPlan": ApplyPlan(payload); break;

            case "aiStatus": _ = AiStatusAsync(Str(payload, "endpoint")); break;
            case "aiProbe": _ = AiProbeAsync(Str(payload, "endpoint")); break;
            case "aiExplain": _ = AiExplainAsync(Str(payload, "endpoint"), Str(payload, "model")); break;
            case "vtLookup": _ = VirusTotalAsync(Str(payload, "key")); break;

            case "compareRun": CompareRun(payload); break;
            case "compareExportPackage": CompareExportPackage(payload); break;

            case "fleetState": PostFleetState(); break;
            case "fleetStart": FleetStart(Int(payload, "port")); break;
            case "fleetStop": FleetStop(); break;
            case "fleetNewCode": FleetNewCode(); break;
            case "fleetDecide": FleetDecide(Str(payload, "agent"), Bool(payload, "approve")); break;
            case "fleetCollect": FleetCollect(Bool(payload, "start")); break;

            case "modalResult": CompleteModal(Str(payload, "id"), Bool(payload, "accepted")); break;
        }
    }

    private void SendBoot() => Post("boot", new
    {
        language = Strings.Language,
        languages = Strings.Available,
        elevated = Privilege.IsElevated(),
        version = BuildInfo.Version,
        sessionRoot = _settings.SessionRoot ?? UserSettings.DefaultSessionRoot,
        ollama = _settings.OllamaEndpoint ?? "http://localhost:11434",
        fleetPort = _settings.FleetPort,
        view = InitialView,
    });

    /// <summary>Loads a session and pushes its projection to the view.</summary>
    public void LoadSession(string path)
    {
        string resolved;
        try { resolved = SessionPaths.Resolve(path); }
        catch (FileNotFoundException)
        {
            Toast(Strings.Format("error.not_a_session", path), "error");
            return;
        }

        try
        {
            _store?.Dispose();
            _store = SessionStore.Open(resolved);
            _sessionPath = resolved;

            _session = _store.LoadSessionInfo();
            if (_session is null)
            {
                Toast(Strings.Format("error.not_a_session", path), "error");
                _store.Dispose();
                _store = null;
                return;
            }

            PushSession();
        }
        catch (Exception ex) when (ex is IOException or Microsoft.Data.Sqlite.SqliteException)
        {
            Toast($"{Strings.T("error.session_open")} {ex.Message}", "error");
        }
    }

    private void PushSession()
    {
        if (_store is null || _session is null) return;

        var request = new ExportRequest
        {
            Scope = ExportScope.Standard,
            Language = Strings.Language,
        };

        Post("session", SessionProjection.BuildModel(_store, _session, request));
    }

    private void RelaunchElevated()
    {
        if (Privilege.IsElevated()) return;

        // Forwarding the currently loaded session means the elevated instance opens
        // where the operator left off rather than on an empty workbench.
        string[] args = _sessionPath is null
            ? Array.Empty<string>()
            : new[] { "--session", _sessionPath };

        if (Privilege.TryRelaunchElevated(args)) Close();
        else Toast(Strings.T("error.needs_admin"), "error");
    }

    private void Reveal(string? path)
    {
        if (string.IsNullOrWhiteSpace(path)) return;

        string full = Path.GetFullPath(path);
        bool isDirectory = Directory.Exists(full);
        if (!isDirectory && !File.Exists(full)) return;

        // ArgumentList rather than a joined string. The path came from a session
        // listing, but a quoted-argument bug here is a command-injection bug, and the
        // API that cannot have one costs nothing.
        var info = new System.Diagnostics.ProcessStartInfo("explorer.exe") { UseShellExecute = true };
        if (isDirectory) info.ArgumentList.Add(full);
        else info.ArgumentList.Add($"/select,{full}");

        try { System.Diagnostics.Process.Start(info); }
        catch (System.ComponentModel.Win32Exception) { }
    }

    private void OnClosingWindow(FormClosingEventArgs e)
    {
        // A running capture holds an ETW session registered with the kernel. Closing
        // the window without stopping it leaves that session consuming buffers until
        // the next run sweeps it up, and loses the after-snapshot entirely.
        if (_capture is null) return;

        DialogResult answer = MessageBox.Show(
            Strings.T("capture.stopping"),
            "CaYaTrace", MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);

        if (answer == DialogResult.Cancel) { e.Cancel = true; return; }

        StopCaptureSynchronously();
    }

    private void Cleanup()
    {
        _captureTimer?.Dispose();
        _store?.Dispose();
        _fleetHost?.Dispose();
    }

    // ------------------------------------------------------------- payload readers

    private static string? Str(JsonElement payload, string name)
        => payload.ValueKind == JsonValueKind.Object
           && payload.TryGetProperty(name, out JsonElement value)
           && value.ValueKind == JsonValueKind.String
            ? value.GetString()
            : null;

    private static int Int(JsonElement payload, string name)
        => payload.ValueKind == JsonValueKind.Object
           && payload.TryGetProperty(name, out JsonElement value)
           && value.TryGetInt32(out int parsed)
            ? parsed
            : 0;

    private static bool Bool(JsonElement payload, string name)
        => payload.ValueKind == JsonValueKind.Object
           && payload.TryGetProperty(name, out JsonElement value)
           && value.ValueKind == JsonValueKind.True;

    private static List<string> StringList(JsonElement payload, string name)
    {
        var result = new List<string>();
        if (payload.ValueKind != JsonValueKind.Object) return result;
        if (!payload.TryGetProperty(name, out JsonElement array)) return result;
        if (array.ValueKind != JsonValueKind.Array) return result;

        foreach (JsonElement item in array.EnumerateArray())
            if (item.ValueKind == JsonValueKind.String && item.GetString() is { Length: > 0 } s)
                result.Add(s);

        return result;
    }
}

/// <summary>
/// Loads the embedded application icon.
/// </summary>
/// <remarks>
/// From a resource rather than a file beside the executable: the shipped build is a
/// single-file bundle where no .ico exists on disk, and a window with the default
/// placeholder icon looks like something that failed to install.
/// </remarks>
internal static class AppIcon
{
    private const string Resource = "CaYaTrace.Assets.cayatrace.ico";

    private static readonly Lazy<System.Drawing.Icon?> Cached = new(() =>
    {
        try
        {
            using Stream? stream = typeof(AppIcon).Assembly.GetManifestResourceStream(Resource);
            return stream is null ? null : new System.Drawing.Icon(stream);
        }
        catch (Exception ex) when (ex is ArgumentException or IOException)
        {
            return null;
        }
    }, LazyThreadSafetyMode.ExecutionAndPublication);

    public static System.Drawing.Icon? Load() => Cached.Value;
}

/// <summary>Resolves the several things an operator might mean by "the session".</summary>
internal static class SessionPaths
{
    public const string DatabaseName = "session.ctdb";

    /// <summary>
    /// Accepts a database file, a session directory, or a session root, in that order
    /// of specificity, and returns the database to open.
    /// </summary>
    public static string Resolve(string input)
    {
        string full = Path.GetFullPath(input);
        if (File.Exists(full)) return full;

        if (Directory.Exists(full))
        {
            string direct = Path.Combine(full, DatabaseName);
            if (File.Exists(direct)) return direct;

            // A session root: take the most recent session inside it.
            string? newest = Directory.EnumerateDirectories(full, "session_*")
                .Select(d => Path.Combine(d, DatabaseName))
                .Where(File.Exists)
                .OrderByDescending(File.GetLastWriteTimeUtc)
                .FirstOrDefault();

            if (newest is not null) return newest;
        }

        throw new FileNotFoundException($"no CaYaTrace session at {full}", full);
    }
}
